version: 0.1
loglevel: debug
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
  tls:
    certificate: /certs/domain.crt
    key: /certs/domain.key
auth:
  token:
    realm: https://192.168.1.55/v2/token
    service: 192.168.1.55:5000
    issuer: RancherReg
    rootcertbundle: /certs/domain.crt 
notifications:
  endpoints:
    - name: portus
      url: https://192.168.1.55/v2/webhooks/events
      timeout: 500ms
      threshold: 5
      backoff: 1s
